services:
  - type: web
    name: blogify-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        scope: env
      - key: JWT_SECRET
        scope: env
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CLOUDINARY_CLOUD_NAME
        scope: env
      - key: CLOUDINARY_API_KEY
        scope: env
      - key: CLOUDINARY_API_SECRET
        scope: env
      - key: ALLOWED_ORIGINS
        value: "*"
